# docker-compose version
version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: xxl-job-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: xxl_job
      MYSQL_BASE_PATH: /Users/admin/program/docker/instance/mysql/v2
    ports:
      - "3306:3306"
    volumes:
      - ./doc/db/tables_xxl_job.sql:/docker-entrypoint-initdb.d/tables_xxl_job.sql:ro
      - /Users/admin/program/docker/instance/mysql/v2/conf:/etc/mysql/conf.d
      - /Users/admin/program/docker/instance/mysql/v2/logs:/var/log/mysql
      - /Users/admin/program/docker/instance/mysql/v2/data:/var/lib/mysql
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - xxl-job-network

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.3.1
    container_name: xxl-job-admin
    environment:
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root 
        --spring.datasource.password=root_pwd
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xxl-job-network

#  xxl-job-executor-sample-springboot:
#    image: xuxueli/xxl-job-executor-sample-springboot:3.3.2-SNAPSHOT
#    container_name: xxl-job-executor-sample-springboot
#    environment:
#      PARAMS: "--xxl.job.admin.addresses=http://xxl-job-admin:8080/xxl-job-admin"
#    ports:
#      - "9999:9999"
#    depends_on:
#      mysql:
#        condition: service_healthy
#      xxl-job-admin:
#        condition: service_healthy
#    networks:
#      - xxl-job-network

networks:
  xxl-job-network:
    driver: bridge
