xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      # 指向admin的地址，端口和context-path要对上
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job, access token
    # 配置是否需要访问token，需要和admin一致
    access-token: default_token
    executor:
      ### xxl-job executor appname
      # 配置执行器名称，在管理页面中需要
      appname: biz-executor
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address: ""
      ### xxl-job executor server-info
      ip: ""
      port: 9999
      ### xxl-job executor log-path
      log-path: ./xxj-job/logs
      ### xxl-job executor log-retention-days
      log-retention-days: 30