server:
  port: 8080

spring:

  # mysql 配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}



